version: '3.3'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - '/home/getesh/Desktop/HIT/DEVOPS:/DEVOPS'
        image: 'jenkins/jenkins:latest'
